In [4]:
import numpy as np #numpy kütüphanesini np olarak ekler.
dizi1=np.array([1, 2,3,4,5])#NumPy dizisi oluşturmak için
dizi2=np.array([1,2,3]) #bir NumPy dizisini atama işlemi için
dizi3=np.array([1,2,3,3.14],dtype=int)#NumPy dizilerini tanımlama sırasında dizideki tüm elemanları tek tipe dönüştürme islemi


In [5]:
dizi1

array([1, 2, 3, 4, 5])

In [6]:
dizi2

array([1, 2, 3])

In [7]:
dizi3

array([1, 2, 3, 3])

In [8]:
birboyut=np.array([1,2,3])# tek bir boyutlu


In [9]:
birboyut

array([1, 2, 3])

In [10]:
ikiboyut = np.array([[1,2,3], [4,5,6]]) #İki boyutlu 


In [12]:
ikiboyut 

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
ucboyut= np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])#Uc boyutlu


In [14]:
ucboyut 

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])