In [5]:
import numpy as np #nump kütüphanesi takma adı ile proje dahil ediyoruz 

In [6]:
dizi=np.full((4,3),5)# 4 satır 3 nsutundan olusan 5 tan olusan dizi
dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [7]:
#yeni bir numpy dizisi olusturuyoruz
np.array([1,2,3])

array([1, 2, 3])

In [12]:
#olusturdugumuz diziyi bir degiskene aktarıyoruz 
dizi=np.array([1,2,3])



In [13]:
dizi

array([1, 2, 3])

In [14]:
#olusturdugumuz diziyi bir degiskene aktarıyoruz 
dizi=np.array(["elma","erik","igde"])

In [15]:
dizi

array(['elma', 'erik', 'igde'], dtype='<U4')

In [16]:
dizi=np.array([1,2,3])
dizi

array([1, 2, 3])

In [17]:
dizi=np.array([1,2,3,3,14])


In [18]:
dizi

array([ 1,  2,  3,  3, 14])

In [ ]:
dizi.dtype #dizinin degisken türünü veriri.nump dizilerinde elemanların hepsi aynı türdendir 

In [ ]:
dtype('float64')

In [20]:
dizi=np.array([1,2,3,14],dtype=int)

In [21]:
dizi

array([ 1,  2,  3, 14])

**numpy ile farklı boyutlarda dizi olusturma**

In [27]:
#bir boyutlu dizi olusturma 
birboyut=np.array([1,2,3,4])
#iki boyutlu dizi olusturma 
ikiboyut=np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])

In [28]:
birboyut

array([1, 2, 3, 4])

In [29]:
ikiboyut

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**numpy yer tutacaklar**

In [30]:
np.zeros(7) #7 sıfırdan olusan tek boyutlu dizi olusturur 

array([0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((2,3),dtype=int) # sıfırdan olusan 2 boyutlu int dizi olusturur 

array([[0, 0, 0],
       [0, 0, 0]])

In [33]:
np.ones(3)

array([1., 1., 1.])

In [34]:
np.full((4,3),5)#5 sayısından olusan 2*3 lük dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [35]:
np.arange(2,22,5)#baslangıc,bitis ve artıs degerine gore dızı olusturma 

array([ 2,  7, 12, 17])

In [37]:
np.linspace(2,10,num=7)#baslangıc ve bıtıs degeri aralıgında belirtilen miktarda esit aralık

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [38]:
np.random.randint(0,10,5)#0-10 aralıgında rastgele 5 sayıdan olusan bir boyutlu dizi

array([3, 0, 6, 4, 4])

In [39]:
np.random.randint(0,10,(5,2))#0-10 aralıgında 5*2 rastgele sayıdan olusan 2 boyutlu dizi

array([[7, 7],
       [0, 2],
       [7, 3],
       [0, 2],
       [6, 7]])

**diziler ile ilgili işlemler**

In [41]:
dizi=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])#dizilerin eleman sayısını ogrenmek icin shape komutu kullanılır
dizi.shape

(3, 4)

In [42]:
#ndim dizi boyutunu ogrenmek icin kullanılır 
dizi.ndim

2

In [43]:
#size dizideki toplam eleman sayısını gosterir 
dizi.size

12

In [44]:
dizi.itemsize #dizideki her bir eleman bayt cinsinden dgerini verir

4